# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-24 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeeBot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aiml_kernel', models.CharField(max_length=102400)),
            ],
        ),
        migrations.AlterField(
            model_name='requestcache',
            name='cache',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AddField(
            model_name='requestcache',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CoffeeBot.UserCache'),
        ),
    ]
